// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC99ab3e1DecodeGithubComVadskevUrlshortInternalEntity(in *jlexer.Lexer, out *Links) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.RawURL = string(in.String())
		case "code":
			out.Slug = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC99ab3e1EncodeGithubComVadskevUrlshortInternalEntity(out *jwriter.Writer, in Links) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.RawURL))
	}
	if in.Slug != "" {
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Slug))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Links) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC99ab3e1EncodeGithubComVadskevUrlshortInternalEntity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Links) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC99ab3e1EncodeGithubComVadskevUrlshortInternalEntity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Links) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC99ab3e1DecodeGithubComVadskevUrlshortInternalEntity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Links) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC99ab3e1DecodeGithubComVadskevUrlshortInternalEntity(l, v)
}
